name = "commerce-theory"
version = "0.1.0"
defaultTargets = ["commerce-theory"]

[[require]]
name = "cslib"
scope = "leanprover"
rev = "v4.29.0"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.1"

[[require]]
name = "timelib"
git = "https://github.com/ammkrn/timelib"
rev = "main"

[[lean_lib]]
name = "CommerceTheory"

[[lean_exe]]
name = "commerce-theory"
root = "Main"
