import CommerceTheory.Foundation
import CommerceTheory.Catalog
import CommerceTheory.Inventory
import CommerceTheory.Pricing
import CommerceTheory.Orders
import CommerceTheory.Accounting
import CommerceTheory.Marketplace
import CommerceTheory.Marketing
import CommerceTheory.B2B
import CommerceTheory.Dropshipping
import CommerceTheory.DropshipProfit
import CommerceTheory.CompetitorPricing
import CommerceTheory.Merchandising
import CommerceTheory.FulfillmentFinance
import CommerceTheory.RiskPrivacy
import CommerceTheory.EventSourcing
import CommerceTheory.EventLanguage
import CommerceTheory.EventReplay
import CommerceTheory.ImplicitInvariants
import CommerceTheory.PostPurchase
import CommerceTheory.Forecasting
import CommerceTheory.InventoryAlgorithms
import CommerceTheory.KeyedTotals
import CommerceTheory.OpportunityPortfolio
import CommerceTheory.OpportunityRanking
import CommerceTheory.Workflow
import CommerceTheory.Summary
import CommerceTheory.Basic

def main : IO Unit :=
  IO.println "Hi!"
